### ISSUE TITLE
Mantainer

### ISSUE THREAD

**Issue by AlbertoMonteiro** [beruic/UriBuilderExtended#2]
I would like to matain this lib

**Comment by beruic** [comment]
That sounds terrific!

For now, just start making pull requests if there is something you'd like to fix, and I will get to promoting you when I can.

**Comment by beruic** [comment]
That was easy! You are now added as a collaborator.

**Comment by AlbertoMonteiro** [comment]
Thanks @beruic !!

**Comment by beruic** [comment]
I also need to make you owner of the NuGet package so you can release new versions to NuGet.

**Comment by AlbertoMonteiro** [comment]
@beruic this is my user: https://www.nuget.org/profiles/albertomonteiro

**Comment by beruic** [comment]
Sorry it took so long. Please confirm that it is done.

**Comment by AlbertoMonteiro** [comment]
Done @beruic thanks!
